url: https://neuvector.github.io/neuvector-helm/core-2.8.3.tgz
version: 104.0.3
additionalCharts:
- workingDir: charts-crd
  crdOptions:
    templateDirectory: crd-template
    crdDirectory: templates
